# Generated by Django 5.2.3 on 2025-07-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobackimage_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="image",
            field=models.ImageField(default="defo", upload_to="documents/"),
        ),
    ]
