# Generated by Django 5.2.3 on 2025-07-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobackimage_app", "0002_alter_document_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="image",
            field=models.ImageField(
                blank=True, default="defo", null=True, upload_to="documents/"
            ),
        ),
    ]
