# Generated by Django 5.2.3 on 2025-07-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobackimage_app", "0003_alter_document_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="output",
            field=models.ImageField(default="output/output.png", upload_to=""),
        ),
    ]
