# Generated by Django 5.2.3 on 2025-07-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nobackimage_app", "0004_alter_document_output"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="output",
        ),
    ]
